### ISSUE TITLE
No force for normal usage

### ISSUE THREAD

**Issue by davidluca3000** [bobhelander/EDForceFeedback#1]
Hello,
I've tried this application (EDFF?) but the joystick feels like there's no force during normal flight, how can I adjust this? I can feel some effects during take off and gear retracting but there's no spring action for when there are no events.
Best regards,
David.

**Comment by bobhelander** [comment]
The joystick should return to your normal spring tension when forces are not being played.  I will look into adding a centering force adjustment.

Thanks, 
Bob

**Comment by bobhelander** [comment]
Release 1.0.0.1 Auto-center turned on
