### ISSUE TITLE
EDForceFeedback.exe

### ISSUE THREAD

**Issue by JusticeFor** [bobhelander/EDForceFeedback#10]
o7 Commander!
Sorry for extremely noob question but I couldn't find the "EDForceFeedback.exe program" in the files. Only files named EDForceFeedback ending with .sln and .csp extensions. Could you help me to figure out how to install your piece of art?
Thank you from another force feedback lover, for developing this code.
Fly safe Cmdr!

**Comment by bobhelander** [comment]
No problem.
The downloads show up as releases in the right hand box on the main page.  Here is the direct link.  Download the EdForceFeedback.zip file.
https://github.com/bobhelander/EDForceFeedback/releases

Bob
