### ISSUE TITLE
[0x80040203]

### ISSUE THREAD

**Issue by Yllelder** [bobhelander/EDForceFeedback#13]
I have a Saitek Cyborg Evo Force, and when I exit the game, the last message is:

**Effect Gear.ffe Exception HRESULT: [0x80040203], Module: [SharpDX.DirectInput], ApiCode: [DIERR_NOTDOWNLOADED/NotDownloaded], Message: Error de sintaxis al tratar de evaluar una cadena de consulta**

I have no problem with the joystick, and no problem with that error, but I put it here in case it is relevant to something.

Thank you very much for creating this fantastic tool.

**Comment by bobhelander** [comment]
Does the force effect play when you raise/lower the landing gear?

Thanks,
Bob

**Comment by Yllelder** [comment]
Yes, the vibration effect works correctly when the landing gear is raised/lower.

**Comment by bobhelander** [comment]
Thank you for the update.  I will attempt to reproduce with my hardware and see if this is an issue.

Enjoy,
Bob
