### ISSUE TITLE
cannot start EDForcefeedback.exe

### ISSUE THREAD

**Issue by Rex-Starlight** [bobhelander/EDForceFeedback#24]
Hello  and thanks for this cool piece of software but im getting an issue where it just doesnt start.
i am using a sidewinder force feedback 2
i installed Net 6.0 manually cause i tought that was missing but it still doesnt launch.
i just get a flash of cmd window opening and closing and thats about it.
i was wondering if im missing something here.

**Comment by bobhelander** [comment]
Try running it from the command line.  If it pops out an error we can catch what it is complaining about.

(I can provide better instructions if these are unclear)
- Press the windows key + R to bring up the run window
- type in cmd.exe and hit enter
- navigate to where you have extracted the files and run EDForceFeedback.exe

Bob

**Comment by Rex-Starlight** [comment]
![image](https://user-images.githubusercontent.com/40770910/222293899-d034d334-4339-4540-8a47-cb0399741d84.png)
apparently it needed the X86 version of .net 6
whoops 
anyway i installed it just now and it just now and it starts up.
thanks for the help, cant wait to test it out.

Rex
