### ISSUE TITLE
EDForceFeedback.exe program

### ISSUE THREAD

**Issue by KBalson** [bobhelander/EDForceFeedback#3]
You write, "EDForceFeedback.exe is a console program that runs during a Elite Dangerous session."

So where is the "EDForceFeedback.exe"  It's not in your posted ZIP archive.  Are you referring to original install software?  If  you are, you need to list that or if not, please add it.

**Comment by bobhelander** [comment]
https://github.com/bobhelander/EDForceFeedback/releases
The release zip file for version 1.0.0.2 does contain the EDForceFeedback.exe file.  Your folder settings may be hiding the .exe extension from you.  The icon for the file has a blue square in it surrounded by lines.

There is no install program.  Just copy these files to any folder and run the EDForceFeedback.exe.  You may then launch Elite Dangerous.  The program will watch for chosen events to appear in the elite dangerous log files and play force feedback effect files to your attached joystick when they appear.  If you want to create your own effects, the zip file also contains the utilities to allow you to create those effects.  The EDForceFeedback.exe.config file tells the program what effect to play for the chosen effect.

Bob

**Comment by KBalson** [comment]
You are incorrectly guessing that File name extensions and hidden items weren't showing, but they are selected to show, and even when looking at the files of  the archive on here, where is it?  Which folder is it in?  EDForceFeedback-master\EDForceFeedback-master\   Is it in this main folder because I have this "EDForceFeedback.sln"   no exe, and if I change that to exe it still doesn't work under Windows 10.

**Comment by KBalson** [comment]
Or is it in EDForceFeedback-master\EDForceFeedback-master\EDForceFeedback\?

In that folder I have "EDForceFeedback.csproj"  also not an .exe, and also doesn't run in Windows 10 if changed to exe.

**Comment by KBalson** [comment]
I see now, that was the difference what you added in the link.

Thank you so much.  That really needs to be linked to http://edcodex.info/?m=tools&entry=480

**Comment by bobhelander** [comment]
Sorry for the delay in response.

You may have downloaded the source code instead of the release zip file.  The .csproj file is only in the source code download.

Bob

**Comment by bobhelander** [comment]
Sorry, this was confusing.

I wanted to link directly to the documentation because the usage is a 
little confusing.

I'm glad you were able to find the release zip file.

O7 - Bob
