### ISSUE TITLE
No force feedback on MS Sidewinder FF2

### ISSUE THREAD

**Issue by mfilia** [bobhelander/EDForceFeedback#5]
Hi there,

I grabbed the latest release and ran the exe prior to running Elite Dangerous but I am not getting any force feedback.  I tested with deploying hardpoints. 

![image](https://user-images.githubusercontent.com/19783286/79937136-1cccdb80-8427-11ea-9825-448e2b8b7956.png)

![image](https://user-images.githubusercontent.com/19783286/79934703-29e6cc00-8421-11ea-815d-f240fe69f383.png)

I also checked X-Plane 11 right after just to be sure. Force feedback works correctly

I am also on discord. Cacazor#7371 if you prefer.

Thanks very much

**Comment by bobhelander** [comment]
Thank you for the detailed output.  
I changed the default settings file to handle the xbox one controller.  
If you would rename the "settings.json" file to "settings.json.bak" and rename "settingsMSFFB2.json" to "settings.json" it will select the correct device and start working.

**Comment by mfilia** [comment]
Thank you very much it worked. I appreciate you taking the time to help.
