### ISSUE TITLE
Good work Bob! 

### ISSUE THREAD

**Issue by Clickzz** [bobhelander/EDForceFeedback#6]
Hello! No issue involved here for the most part. 
Just wanted to add a few effects i developed with the tool you hand in the EDForceFeedback files.
I saw you updated not long ago but i was wondering if someone with my joystick (Logitech Force3DPRO) needed my "settings file" and effects folder. 
Also on that matter i was wondering if you wanted my fx to try and see i you like them, ill keep working on them. Ill sure try the april update.

Best regards and thank you very much for developing all of this. I wouldn't got involved in the game if it wasn't for you and im loving it. :D 
Thanks again!

**Comment by bobhelander** [comment]
I would like to include your files.  You can message me directly github@bobhelander.com.

Thank you for contributing!

Bob
