### ISSUE TITLE
Teensy 2.0 Adapter Sidewinder Fix

### ISSUE THREAD

**Issue by pladombrowski** [bobhelander/EDForceFeedback#7]
Hello, first of all I want to thank you for the great job!
I have a Sidewinder ForceFeedBack Pro running with a Teensy 2.0 db15-usb adapter using https://github.com/tloimu/adapt-ffb-joy and your code perfectly.
I had to only to make a little tweak to get all devices on MicrosoftSidewinder.cs as follow: 

`directInputDevices.AddRange(directInput.GetDevices());
//directInputDevices.AddRange(directInput.GetDevices(DeviceType.Joystick, DeviceEnumerationFlags.AllDevices));
//directInputDevices.AddRange(directInput.GetDevices(DeviceType.Gamepad, DeviceEnumerationFlags.AllDevices));
//directInputDevices.AddRange(directInput.GetDevices(DeviceType.Driving, DeviceEnumerationFlags.AllDevices));`

Because my joystick wasn't recognized by the DeviceType enum.

**Comment by bobhelander** [comment]
I like the change.  The enumeration of the devices always seems to miss something.

Thank you for the help!

Bob

**Comment by S1L1C0N1** [comment]
Hi, Is it possible you make your fix available to other users? I also recently completed the teensy adapter for the FFB Pro.
